#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat May 09 17:30:42 CST 2026
maven-metadata-central-direct.xml.lastUpdated=1778319042983
