spring:
  application:
    name: recommend

  datasource:
    url: jdbc:mysql://localhost:3306/recommend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_0900_ai_ci
    username: root
    password: 2004zyta
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false

  sql:
    init:
      mode: always
      continue-on-error: true
      encoding: UTF-8

  data:
    redis:
      host: ${REDIS_HOST:192.168.253.161}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:2004zyta}
      database: ${REDIS_DB:0}
      timeout: ${REDIS_TIMEOUT:3000ms}
      ssl:
        enabled: ${REDIS_SSL:false}
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 1
          max-wait: 3000ms
        shutdown-timeout: 100ms
      connect-timeout: 2000ms
      client-type: lettuce
    redis.repositories.enabled: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:3264299498@qq.com}
    password: ${MAIL_PASSWORD:tlcuhhqcqepycjbi}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080

recommend:
  association:
    precompute-interval-ms: 900000
    initial-delay-ms: 60000
    neighbor-limit: 120
  upload-dir: uploads
