-- Tokopedia鍟嗗搧鏁版嵁瀵煎叆
-- 鐢熸垚鏃堕棿: 2026-05-22 23:03:23

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE items;

INSERT INTO items (name, category, price, image_url, description) VALUES ('Wellness Omega-3 Fish Oil [75 Softgels] - Banded', 'Uncategorized', 385000, NULL, 'Wellness Omega-3 Fish Oil [75 Softgels]');
INSERT INTO items (name, category, price, image_url, description) VALUES (' EPA', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Vitamin & Suplemen', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/kesehatan}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Wellness Dynovite Child Multivitamin', 'Uncategorized', 192500, NULL, 'Wellness Dynovite Child Multivitamin');
INSERT INTO items (name, category, price, image_url, description) VALUES (' Beta Carotene', ' Iron', 1, NULL, ' Vitamin B12');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Vitamin & Suplemen', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/kesehatan}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Wellness Excell-C 500MG [60 Tablets]', 'Uncategorized', 188000, NULL, 'Wellness Excell-C 500mg [60 Tablets]');
INSERT INTO items (name, category, price, image_url, description) VALUES (' Citrus Bioflavonoid', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Vitamin & Suplemen', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/kesehatan}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Wellness Natural Vitamin E 400 IU [60 Softgels] - Banded', 'Uncategorized', 475000, NULL, 'Wellness Natural Vitamin E 400 IU [60 Softgels]');
INSERT INTO items (name, category, price, image_url, description) VALUES (' reproduksi', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' sehingga mempunyai khasiat/potensi yang jauh lebih tinggi daripada pada vit E sintetis (dl-alpha tocopheryl)', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' anti kanker dan anti aging', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Vitamin & Suplemen', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/kesehatan}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Bio Oil Dry Skin Gel 100ml & Bio Oil 25ml', 'Uncategorized', 189000, NULL, 'Bio Oil Dry Skin Gel 100ml &amp; Bio Oil 25ml');
INSERT INTO items (name, category, price, image_url, description) VALUES (' menjadikannya pelembab intensif.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' lotion dan body butter pada umumnya berbahan dasar air. Sebagian besar air ini menguap begitu saja saat bersentuhan dengan kulit Anda. Hal ini yang seringkali menyebabkan sensasi dingin yang Anda ras', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' sehingga membuat produk 100% aktif dan efektif untuk kulit kering.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' formulasi Bio-Oil Gel Kulit Kering memadukan emollients seperti shea butter dan humectants seperti glycerine dan urea', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' tidak meninggalkan rasa lengket', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' sedikit penggunaan Bio-Oil Gel Kulit Kering sudah mampu memberikan kelembaban pada kulit secara maksimal', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' dapat digunakan keseluruh tubuh', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' menyamarkan bekas luka', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pertumbuhan pada remaja', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pencerah kulit atau paparan sinar matahari yang berlebihan.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' air dengan kandungan kimia yang tinggi', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap. Gunakan minimal selama 3 bulan. Jangan digunakan pada kulit yang luka.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat pada bagian perut', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' oleskan dua kali sehari', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap. Gunakan minimal selama 3 bulan.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Kulit', 'Uncategorized', 0, NULL, '{name:Perawatan Tubuh');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Bio Oil - Skincare Oil Natural 200ml', 'Uncategorized', 453000, NULL, 'Bio Oil - Skincare Oil Natural 200ml');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pertumbuhan pesat pada remaja dan periode kenaikan berat badan', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' serta membantu mempertahankan kelembaban', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' Sunflower Seed Oil', ' Bisabolol', 0, NULL, ' Rosehip Oil');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Kulit', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/perawatan-tubuh}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Bio Oil - Body Lotion 175ml', 'Uncategorized', 193000, NULL, 'Bio Oil - Body Lotion 175ml');
INSERT INTO items (name, category, price, image_url, description) VALUES (' namun memiliki kandungan minyak tinggi sebesar 42%. Kombinasi unik antara kelembutan ultra-ringan dan kandungan minyak yang tinggi ini dapat terwujud berkat formulasi inovatif &#39;kocok sebelum digu', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' Vitamin F', ' Sodium PCA', 0, NULL, ' Tocopherol');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Kulit', 'Uncategorized', 0, NULL, '{name:Perawatan Kulit');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Bio Oil (125ml) + Bio Oil Dry Skin Gel 100ml', 'Uncategorized', 336000, NULL, 'Bio Oil - Skincare Oil125mL (Exp.Date : November 2027)');
INSERT INTO items (name, category, price, image_url, description) VALUES (' menyamarkan bekas luka', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap. Gunakan minimal selama 3 bulan. Jangan digunakan pada kulit yang luka.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat Bio-Oil pada bagian perut', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' oleskan Bio-Oil dua kali sehari', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap. Gunakan minimal selama 3 bulan.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' mandi', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' menjadikannya pelembab intensif.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' lotion dan body butter pada umumnya berbahan dasar air. Sebagian besar air ini menguap begitu saja saat bersentuhan dengan kulit Anda. Hal ini yang seringkali menyebabkan sensasi dingin yang Anda ras', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' sehingga membuat produk 100% aktif dan efektif untuk kulit kering.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' formulasi Bio-Oil Gel Kulit Kering memadukan emollients seperti shea butter dan humectants seperti glycerine dan urea', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' tidak meninggalkan rasa lengket', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' sedikit penggunaan Bio-Oil Gel Kulit Kering sudah mampu memberikan kelembaban pada kulit secara maksimal', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' dapat digunakan keseluruh tubuh', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Kulit', 'Uncategorized', 0, NULL, '{name:Perawatan Kulit');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Bio Oil- (60 ml) -2 pcs', 'Uncategorized', 267200, NULL, 'Bio Oil- (60 ml) -2 pcs');
INSERT INTO items (name, category, price, image_url, description) VALUES (' menyamarkan bekas luka', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap. Gunakan minimal selama 3 bulan. Jangan digunakan pada kulit yang luka.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat Bio-Oil pada bagian perut', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' oleskan Bio-Oil dua kali sehari', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap. Gunakan minimal selama 3 bulan.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' pijat lembut menggunakan ujung jari dengan gerakan melingkar sampai benar-benar terserap.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' mandi', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Kulit', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/perawatan-tubuh}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('TWIN PACK - Dacco Mama Pad Premium Isi 38pcs - Breast Pad', 'Uncategorized', 114200, NULL, 'Isi Paket :');
INSERT INTO items (name, category, price, image_url, description) VALUES (' disesuaikan dengan bentuk payudara Ibu.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' MM = Bulan', 'Uncategorized', 0, NULL, '{name:Ibu & Bayi');
INSERT INTO items (name, category, price, image_url, description) VALUES ('TRIPLE PACK - Dacco Baby Clean & Soft Wipes 80pcs Pure Water 99%', 'Uncategorized', 118800, NULL, 'Isi:');
INSERT INTO items (name, category, price, image_url, description) VALUES (' MM = Bulan', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Bayi', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/ibu-bayi/perawatan-bayi}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Dacco Pembalut Wanita Bersalin & Nifas L - Isi 4 Pcs', 'Uncategorized', 27300, NULL, 'Dacco Pembalut Wanita Bersalin &amp; Nifas Ukuran L - Isi 4Pcs');
INSERT INTO items (name, category, price, image_url, description) VALUES (' mampu menyerap banyak cairan secara cepat sehingga permukaan kering.  ', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' mencegah cairan tembus/bocor', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('5 cm', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('5 cm', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' MM = Bulan', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/perawatan-tubuh}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Dear Body Hair Parfume - 100ml All Variant - Simfoni Vanilla', 'Uncategorized', 33476, NULL, 'BUY 1 GET 1 . DAPAT 2 PCS HAIR PARFUME');
INSERT INTO items (name, category, price, image_url, description) VALUES (' dengan adanya kandungan tabir surya mempu melindungi rambut dari sinar UV.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' didesain praktis dengan tutup spray dan ukuran travel yang mudah dibawa bepergian.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Rambut', 'product_variant_id:null', 0, NULL, '{name:Perawatan Tubuh');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Byphasse Waterproof Biphasic Micellar Water 500ml - Make up Remover', 'Uncategorized', 110600, NULL, 'Untuk semua jenis kulit, bahkan yang paling sensitif sekalipun.');
INSERT INTO items (name, category, price, image_url, description) VALUES (' dan fase berminyak yang membantu menghilangkan lapisan anti air yang paling tahan riasan pada wajah', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' atau perlu dibilas.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' menghilangkan make-up dan memurnikan wajah', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' bahkan yang paling sensitif sekalipun.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' menghapus make-up', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Pembersih Make Up', 'Uncategorized', 0, NULL, '{name:Pembersih Make Up');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Dear Body Hair Parfume Sugar Bloom - 100ml', 'Uncategorized', 33476, NULL, 'BUY 1 GET 1 . DAPAT 2 PCS HAIR PARFUME');
INSERT INTO items (name, category, price, image_url, description) VALUES (' dengan adanya kandungan tabir surya mempu melindungi rambut dari sinar UV.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' didesain praktis dengan tutup spray dan ukuran travel yang mudah dibawa bepergian.', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perawatan Rambut', 'url:https://www.tokopedia.com/p/perawatan-tubuh/perawatan-rambut}', 0, NULL, 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/10/13/71d196b4-d41b-4ed0-8855-5c5d4b95dfc6.jpg');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Byphasse Caresse Shower Cream Rosehip - 2 Liter', 'Uncategorized', 110000, NULL, 'ED AUG 2022 Sabun mandi cair bertekstur krim dengan minyak rosehip Chili membersihkan kulit Anda dengan lembut. ');
INSERT INTO items (name, category, price, image_url, description) VALUES (' lembut', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perlengkapan Mandi', 'Uncategorized', 0, NULL, 'url:https://www.tokopedia.com/p/perawatan-tubuh}');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Leivy Double Moisturising - Goats Milk Bar Soap 85gr', 'Uncategorized', 13709, NULL, 'Dengan harga lebih ekonomis, Leivy Double Moisturising Bar Soap membantu memberikan kelembaban dua kali lipat pada kulit anda. Susu kambing, yg merupakan sebuah formula alami untuk mencegah kekeringan, melindungi kulit dengan baik, dan melembapkan meningkatkan kelembutan kulit. membersihkan tanpa merusak lapisan kulit alami kita.  ');
INSERT INTO items (name, category, price, image_url, description) VALUES (' B', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES (' B', 'Uncategorized', 0, NULL, '');
INSERT INTO items (name, category, price, image_url, description) VALUES ('Perlengkapan Mandi', 'url:https://www.tokopedia.com/p/perawatan-tubuh/perlengkapan-mandi}', 0, NULL, 'https://images.tokopedia.net/img/cache/700/VqbcmM/2024/10/30/ac65ab96-6701-48b5-8a9c-927fdcc3c2b0.jpg');

SET FOREIGN_KEY_CHECKS=1;
SELECT COUNT(*) AS total_items_inserted FROM items;
